# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/spdk/spdk/go", "github.com/square/certstrap"]

# golang/protobuf gets replaced with gogo/protobuf by
# post-processing the vendored sources, see "update_dep"
# in the Makefile.
ignored = [
  "github.com/golang/protobuf/proto",
  "github.com/golang/protobuf/ptypes",
  "github.com/golang/protobuf/ptypes/any",
  "github.com/golang/protobuf/ptypes/duration",
  "github.com/golang/protobuf/ptypes/timestamp",
  "github.com/golang/protobuf/ptypes/wrappers",
]

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/spdk/spdk"
    go-tests = false
    unused-packages = false

[[constraint]]
  name = "github.com/spdk/spdk"
  # Because we need https://review.gerrithub.io/c/spdk/spdk/+/430460/ for RBD.
  source = "github.com/pohly/spdk"
  branch = "rbd"

# We are based on CSI v0.3.0 and must pull in the right version of the spec
# and the corresponding csi-test.
[[override]]
  name = "github.com/container-storage-interface/spec"
  version = "0.3"

[[override]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "0.3"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/cloud-provider"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/cluster-bootstrap"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/csi-api"
  version = "kubernetes-1.13.1"
[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.1"

# Doesn't do proper releases.
[[override]]
  name = "k8s.io/kube-openapi"
  branch = "master"

# Also no proper releases.
[[override]]
  name = "k8s.io/utils"
  branch = "master"

[[override]]
  # kubernetes/pkg/util/parsers/parsers.go needs the new reference.ParseNormalizedNamed
  # API call, which isn't yet in any stable release.
  name = "github.com/docker/distribution"
  branch = "master"

# This prevents dep from pulling an empty repo for gopkg.in/fsnotify.v1,
# something that it does not recover from.
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
