apiVersion: v1
kind: ServiceAccount
metadata:
  name: oim-malloc-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oim-malloc-provisioner-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oim-malloc-external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: oim-malloc-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oim-malloc-attacher-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oim-malloc-external-attacher-runner
subjects:
- kind: ServiceAccount
  name: oim-malloc-sa
  namespace: default
