kind: Pod
apiVersion: v1
metadata:
  name: oim-malloc-app
spec:
  nodeSelector:
    intel.com/oim: "1"
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: oim-malloc-pvc
